user registration test
varff/InnoUserService pull request #11
Opened 2022-08-26 08:53 UTC by varff

2022-08-29 08:59 UTC, DrGermanius reviewed
Is it ready for review?

2022-08-29 12:23 UTC, varff commented
Nope

2022-09-01 14:56 UTC, DrGermanius requested changes

2022-09-01 14:56 UTC, DrGermanius commented on pkg/handlers/auth_handler.go
> +	resp    models.UserResponse
I don't agree with these solution

2022-09-01 14:56 UTC, DrGermanius commented on pkg/handlers/auth_handler.go
> +	resp    models.UserResponse
Didn't get the point of this

2022-09-01 14:56 UTC, DrGermanius commented on pkg/handlers/auth_handler.go
> +	resp    models.UserResponse
If you need to use different sctures you will add all of them? I think it's not necessary

2022-09-01 14:56 UTC, DrGermanius commented on pkg/handlers/service_handler_test.go
> +	mockIService.EXPECT().DeleteUser(gomock.Any()).Return(apperrors.ErrNotFound)
Are you sure about using any()? It must be only in corner-cases

2022-09-01 14:56 UTC, DrGermanius commented on pkg/models/response.go
> +}
nonononono

2022-09-01 14:56 UTC, DrGermanius commented on pkg/models/response.go
> +}
let's talk about it later

2022-09-07 19:40 UTC, DrGermanius requested changes
Please fix and merge

2022-09-07 19:40 UTC, DrGermanius commented on pkg/handlers/service_handler_test.go
> +	}
need to use t.Fatal or something

2022-09-08 07:02 UTC, merged