Feature/logging
varff/InnoUserService pull request #6
Opened 2022-08-17 10:09 UTC by varff

2022-08-17 16:54 UTC, DrGermanius requested changes

2022-08-17 16:54 UTC, DrGermanius commented on cmd/main.go
> +	"github.com/gin-contrib/pprof"
please attach screenshots with pprof info

2022-08-17 16:54 UTC, DrGermanius commented on pkg/handlers/service_handler.go
> +		err = apperrors.ErrValidError
don't understand that

2022-08-17 16:54 UTC, DrGermanius commented on pkg/logging/logging.go
> +	uri := "mongodb://" + mongoHost + ":" + mongoPort
better to use sprintf

2022-08-18 07:30 UTC, varff commented on cmd/main.go
> +	"github.com/gin-contrib/pprof"
![image](https://user-images.githubusercontent.com/62174550/185335266-04a6bcc6-ef2e-4d00-a76e-a69d0a7a2175.png)
![image](https://user-images.githubusercontent.com/62174550/185335469-bbceeed3-afa7-467f-a951-3b3a5b036983.png)
![image](https://user-images.githubusercontent.com/62174550/185335607-402be37b-a65a-4bcc-a0a9-d46d31484551.png)
![image](https://user-images.githubusercontent.com/62174550/185335667-e8a5c864-d387-4d5c-ba38-30cae9cf86e4.png)

2022-08-18 10:29 UTC, varff commented on cmd/main.go
> +	"github.com/gin-contrib/pprof"
[profile.pb.gz](https://github.com/varff/InnoUserService/files/9372663/profile.pb.gz)

2022-08-18 10:32 UTC, DrGermanius approved these changes

2022-08-18 10:32 UTC, DrGermanius commented on pkg/logging/logging.go
> +	_, errM := db.errCol.InsertOne(context.TODO(), insertion)
err

2022-08-18 11:13 UTC, merged